version: '3.8'

services:
  # Streamlit Dashboard
  dashboard:
    build: .
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app/src
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    volumes:
      - ./data:/app/data:ro
      - ./models:/app/models:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - uber-forecast-net

  # FastAPI Backend
  api:
    build: .
    command: ["python", "api/main.py"]
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - ./data:/app/data:ro
      - ./models:/app/models:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - uber-forecast-net

  # Nginx Reverse Proxy (Production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - dashboard
      - api
    restart: unless-stopped
    networks:
      - uber-forecast-net

networks:
  uber-forecast-net:
    driver: bridge

volumes:
  model_data:
  app_data: